name: android build

on:
  workflow_call:
    secrets: FLUTTER_VERSION

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: ${{ secrets.FLUTTER_VERSION }}

      # Get flutter dependencies.
      - run: |
          flutter pub get

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
