name: android build

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      SLACK_INCOMING_WEBHOOK_URL:
        required: true

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: ${{ vars.FLUTTER_VERSION }}

      # Get flutter dependencies.
      - run: |
          flutter pub get

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Send to slack
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Github Actions実行結果: ${{ job.status }}\nAndroid APKダウンロードリンク: ${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Github Actions実行結果: ${{ job.status }}\nAndroid APKダウンロードリンク: ${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
