name: ios build

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: '3.22.2'

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Get flutter dependencies.
      - run: |
          flutter pub get

      # Build apk.
      - run: flutter build ios --simulator

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/ios/iphonesimulator/Runner.app
