name: staging build

on:
  push:
    branches:
      - main

jobs:
  android-build:
    uses: ./.github/workflows/android-build.yml
    with:
      env: staging
    secrets: inherit

  ios-build:
    needs: android-build
    uses: ./.github/workflows/ios-build.yml
    with:
      env: staging
    secrets: inherit
